/**
 * Type definitions for the client-side ML inference pipeline.
 *
 * The model is a logistic regression trained offline in Python (Scikit-learn).
 * These types describe the JSON contract between the training script and the
 * TypeScript inference engine so that both sides stay in sync.
 */

// ---------------------------------------------------------------------------
// Model weights JSON schema — loaded at runtime from model-weights.json
// ---------------------------------------------------------------------------

/** Standard scaler parameters exported from sklearn.preprocessing.StandardScaler */
export interface ScalerParams {
  /** Per-feature mean values used during training */
  mean: number[]
  /** Per-feature standard deviation values used during training */
  std: number[]
}

/**
 * Maps raw categorical string values to their numeric encoding.
 * Example: { "Stage I": 1, "Stage II": 2, "Stage III": 3, "Stage IV": 4 }
 *
 * The TS inference engine looks up patient fields in these maps so there is
 * zero hardcoded encoding logic — everything is data-driven from the JSON.
 */
export interface CategoricalMaps {
  sex: Record<string, number>
  stageOfTheCancer: Record<string, number>
  insuranceType: Record<string, number>
  rationCardColor: Record<string, number>
  patientStatus: Record<string, number>
}

/** The full model weights file shape — see lib/ml/model-weights.json */
export interface ModelWeights {
  /** Semantic version of this model snapshot */
  version: string
  /** ISO 8601 timestamp of when the model was trained */
  trainedAt: string
  /**
   * Ordered list of feature names. The TS feature extractor must produce a
   * numeric array whose indices match this ordering exactly.
   */
  features: string[]
  /** Logistic regression coefficients — one per feature */
  weights: number[]
  /** Logistic regression intercept (bias) term */
  intercept: number
  /** StandardScaler params for z-score normalization before inference */
  scaler: ScalerParams
  /**
   * Categorical encoding maps exported from the Python training script.
   * These are the single source of truth — the TS engine never hardcodes
   * string → number mappings.
   */
  categoricalMaps: CategoricalMaps
  /** Training-time metrics for documentation / display purposes */
  metrics: {
    accuracy: number
    f1: number
    samplesUsed: number
  }
}

// ---------------------------------------------------------------------------
// Inference output types — consumed by React components
// ---------------------------------------------------------------------------

/** Risk tier buckets displayed in the UI */
export type RiskTier = 'Low' | 'Medium' | 'High'

/** The result of running inference on a single patient record */
export interface RiskResult {
  /** Probability of non-adherence, range [0, 1] */
  score: number
  /** Human-readable risk tier derived from score thresholds */
  tier: RiskTier
  /**
   * Top contributing factors explaining the score.
   * Computed as abs(standardized_feature * weight), sorted descending.
   * Contains the 3 largest contributors with human-readable labels.
   */
  factors: string[]
}

// ---------------------------------------------------------------------------
// Cross-language test vectors — used to validate TS ↔ Python parity
// ---------------------------------------------------------------------------

/** A single test case generated by the Python training script */
export interface TestVector {
  /** Raw patient-like feature values keyed by feature name */
  rawFeatures: Record<string, number>
  /** The expected risk score (probability) from Python's predict_proba */
  expectedScore: number
}
